version: '3'
services:
  react:
    build:
      context: ./react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  
  express:
    build:
      context: ./express
    ports:
      - "5000:5000"